import { SpecName, ClassName, ClassSpec } from "./types/specs";

const specs: Record<SpecName, ClassSpec> = {
    [SpecName.boomie]: {
        id: SpecName.boomie,
        className: ClassName.Druid,
        humanLabel: "Balance Druid",
        canRangedDPS: true,
        canBombs: true,
        canOffheal: true,
    },
    [SpecName.feral]: {
        id: SpecName.feral,
        className: ClassName.Druid,
        humanLabel: "Feral Druid",
        canMeleeDPS: true,
        canBombs: true,
        canBombsNonIdeal: true,
    },
    [SpecName.resto]: {
        id: SpecName.resto,
        className: ClassName.Druid,
        humanLabel: "Resto Druid",
        canRaidHeal: true,
    },
    [SpecName.flexDruid]: {
        id: SpecName.flexDruid,
        className: ClassName.Druid,
        humanLabel: "Resto/Balance Flex Druid",
        healOrRanged: { heal: SpecName.resto, ranged: SpecName.boomie },
    },
    [SpecName.meleeHunter]: {
        id: SpecName.meleeHunter,
        className: ClassName.Hunter,
        humanLabel: "Melee Hunter",
        canMeleeDPS: true,
    },
    [SpecName.rangedHunter]: {
        id: SpecName.rangedHunter,
        className: ClassName.Hunter,
        humanLabel: "Ranged Hunter",
        canRangedDPS: true,
    },
    [SpecName.frostMage]: {
        id: SpecName.frostMage,
        className: ClassName.Mage,
        humanLabel: "Frost Mage",
        canRangedDPS: true,
    },
    [SpecName.fireMage]: {
        id: SpecName.fireMage,
        className: ClassName.Mage,
        humanLabel: "Fire Mage",
        canRangedDPS: true,
        canBombs: true,
    },
    [SpecName.arcaneMage]: {
        id: SpecName.arcaneMage,
        className: ClassName.Mage,
        humanLabel: "Arcane Mage",
        canRangedDPS: true,
        canTankHeal: true,
    },
    [SpecName.flexMage]: {
        id: SpecName.flexMage,
        className: ClassName.Mage,
        humanLabel: "Fire/Arcane Flex Mage",
        healOrRanged: { heal: SpecName.arcaneMage, ranged: SpecName.fireMage },
    },
    [SpecName.holyPal]: {
        id: SpecName.holyPal,
        className: ClassName.Paladin,
        humanLabel: "Holy Paladin",
        canTankHeal: true,
        canCleanseDisease: true,
        canCleanseMagic: true,
        canResistAura: true,
    },
    [SpecName.retPal]: {
        id: SpecName.retPal,
        className: ClassName.Paladin,
        humanLabel: "Ret Paladin",
        canMeleeDPS: true,
        canKick: true,
        canCleanseDisease: true,
        canCleanseMagic: true,
        canResistAura: true,
    },
    [SpecName.tankPal]: {
        id: SpecName.tankPal,
        className: ClassName.Paladin,
        humanLabel: "Tank Paladin",
        canTank: true,
        canKick: true,
        canResistAura: true,
        canCleanseDisease: true,
        canCleanseMagic: true,
        canMeleeDPS: true,
    },
    [SpecName.healPriest]: {
        id: SpecName.healPriest,
        className: ClassName.Priest,
        humanLabel: "Holy/Disc Priest",
        canTankHeal: true,
        canRaidHeal: true,
        canCleanseDisease: true,
        canCleanseMagic: true,
    },
    [SpecName.shadow]: {
        id: SpecName.shadow,
        className: ClassName.Priest,
        humanLabel: "Shadow Priest",
        canRangedDPS: true,
        canOffheal: true,
        canCleanseDisease: true,
        canCleanseMagic: true,
        canMajorArmorDebuff: true,
    },
    [SpecName.tankRogue]: {
        id: SpecName.tankRogue,
        className: ClassName.Rogue,
        humanLabel: "Tank Rogue",
        canTank: true,
        canKick: true,
        canMeleeDPS: true,
    },
    [SpecName.dpsRogue]: {
        id: SpecName.dpsRogue,
        className: ClassName.Rogue,
        humanLabel: "DPS Rogue",
        canKick: true,
        canMeleeDPS: true,
    },
    [SpecName.tankWarlock]: {
        id: SpecName.tankWarlock,
        className: ClassName.Warlock,
        humanLabel: "Tank Warlock",
        canTank: true,
        canRangedDPS: true,
        canBombs: true,
    },
    [SpecName.dpsWarlock]: {
        id: SpecName.dpsWarlock,
        className: ClassName.Warlock,
        humanLabel: "DPS Warlock",
        canRangedDPS: true,
        canBombs: true,
    },
    [SpecName.tankWarrior]: {
        id: SpecName.tankWarrior,
        className: ClassName.Warrior,
        humanLabel: "Tank Warrior",
        canTank: true,
        canKick: true,
        canMeleeDPS: true,
        canMajorArmorDebuff: true,
    },
    [SpecName.dpsWarrior]: {
        id: SpecName.dpsWarrior,
        className: ClassName.Warrior,
        humanLabel: "DPS Warrior",
        canKick: true,
        canMeleeDPS: true,
        canMajorArmorDebuff: true,
    },
};

export default specs;
